-- AlterTable
ALTER TABLE "Area" ADD COLUMN     "montoMaximo" DOUBLE PRECISION NOT NULL DEFAULT 150,
ADD COLUMN     "montoTotal" DOUBLE PRECISION NOT NULL DEFAULT 1000,
ADD COLUMN     "saldoActual" DOUBLE PRECISION NOT NULL DEFAULT 1000,
ADD COLUMN     "umbralAlerta" DOUBLE PRECISION NOT NULL DEFAULT 200;
